### ISSUE TITLE
Text exceeds the div boundary for some font family

### ISSUE THREAD

**Issue by vinujan59** [saltycrane/use-fit-text#11]
Thanks for this awesome library

When fitting text with web fonts sometime letters goes over the div border

is there any way to have a padding to avoid this?

![image](https://user-images.githubusercontent.com/11666269/101639729-98d56b80-3a6a-11eb-8df9-3f5afb56c90f.png)

**Comment by vinujan59** [comment]
Managed with `display: box; padding: 5px` instead of `display: flex`

**Comment by vinujan59** [comment]
even with above work around some times the text exceeds the border 

![image](https://user-images.githubusercontent.com/11666269/101881717-c4259b00-3bcf-11eb-94ee-83526c98a6e3.png)

**Comment by saltycrane** [comment]
Hi @vinujan59, I'm glad you are trying out the library.

Are you seeing this message in the console?

```
[use-fit-text] reached `minFontSize = 20` without fitting text
```

If so, can you try changing `minFontSize` to a smaller value?

If not, would you fork this CodeSandbox example and change the code so that it demonstrates your problem?
https://codesandbox.io/s/use-fit-text-gfont-example-236v3?file=/pages/index.js

**Comment by vinujan59** [comment]
Hi @saltycrane, Your library is awesome, Thank you for the prompt reply

I was able to reproduce the scenario I faced 

Please find it here - https://codesandbox.io/s/use-fit-text-gfont-example-forked-zvjqc?file=/pages/index.js 

Thanks,

Edit - Please note that, when I open the same code sandbox in another page, the issue goes away, so attaching the screenshot

![image](https://user-images.githubusercontent.com/11666269/102168786-d94e4280-3ecb-11eb-8694-8e2b0fbc54a6.png)

**Comment by vinujan59** [comment]
I think the issue here is font is being slanted/italic

can’t we use something like this https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics to compare text overflowed

But in library point of view, we need to observe for the width changes, so it is better to create custom component

**Comment by saltycrane** [comment]
Hi @vinujan59, thank you very much for the reproduction in Codesandbox-- it is very helpful. Unfortunately I'm not sure how to fix this issue. If this were in my project, I'd probably hack it with some right padding. Is the text you are fitting dynamic (there is sometimes a lot of text and sometimes a little text), so a fixed padding does not work?

I'm not familiar with `TextMetrics` but isn't it an API only for `<canvas>`? I will try to think about it some more.

**Comment by vinujan59** [comment]
Hi @saltycrane, Sorry for the late reply.

In my case padding didn't work. Text exceeded the boundary even with the padding as well.

I came up with a solution based on canvas to solve above issue. created a custom component called `useCustomFontFitText`

some changes from `useFitText` is

```
const textWidth = useMemo(() => getTextWidth(canvas, text, canvasFont), [canvas, text, canvasFont]);
const canvas = useMemo(() => document.createElement('canvas'), []);
const getTextWidth = (canvas, text, font) => {
    const context = canvas.getContext('2d');

    context.font = font;
    const { actualBoundingBoxLeft, actualBoundingBoxRight } = context.measureText(text);
    return Math.ceil(Math.abs(actualBoundingBoxLeft) + Math.abs(actualBoundingBoxRight)) + 20;
};

....
const isOverflow = !!ref.current && (ref.current.scrollHeight > ref.current.offsetHeight || textWidth > ref.current.offsetWidth);
....
```

This solution fixed the issue.


Edit - This only support for one line text and limited number of characters

**Comment by saltycrane** [comment]
hi @vinujan59 thank you very much for providing your solution. I tried it out and see it solving the problem. I agree with you that it should probably be a separate React hook since it uses a different approach to fitting the text.

**Comment by vinujan59** [comment]
Thanks again for the effort. I really like the idea. Please do let me if there is anything I can help out as a token of appreciation. 

PS. closing this thread
