### ISSUE TITLE
Cannot find type definition file for 'next'.

### ISSUE THREAD

**Issue by all-bear** [saltycrane/use-fit-text#4]
Hi, probably this is stupid question (sorry, but I'm not really good at Typescript).

But during the build or typescript project I'm getting this error:

```
node_modules/use-fit-text/dist/index.d.ts:2:23 - error TS2688: Cannot find type definition file for 'next'.
```

the question is, do you really need this line `/// <reference types="next" />` in file `dist/index.d.ts` ?

**Comment by all-bear** [comment]
Sorry, my mistake I didn't check example where `next` is used, my first thought was that this is not related with `next` at all

**Comment by saltycrane** [comment]
@all-bear sorry about that. I removed the `<reference types="next" />` line in [v2.1.2](https://www.npmjs.com/package/use-fit-text/v/2.1.2)
