### ISSUE TITLE
How to be sure that redraw is finished ?

### ISSUE THREAD

**Issue by TeaBough** [saltycrane/use-fit-text#6]
I'm using puppeteer to print a page that need font to be resized. Not all of my font get's resized when printing the page... How can I be sure the page is done refiting my font ?

**Comment by saltycrane** [comment]
Hi @TeaBough, if I added an `onFinish` callback to `useFitText`, would that help? It would run when useFitText has finished fitting the text.

**Comment by TeaBough** [comment]
Yes definitely !

**Comment by saltycrane** [comment]
Hi @TeaBough, I added `onStart` and `onFinish` callbacks in [`use-fit-text@2.2.0`](https://www.npmjs.com/package/use-fit-text/v/2.2.0). See the [example usage here](https://github.com/saltycrane/use-fit-text/blob/v2.2.0/examples/pages/index.tsx#L33-L39). Hope it helps!

**Comment by TeaBough** [comment]
Awesome @saltycrane !
